name: settingsheet_manager
description: "A new Flutter project."
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  flutter_launcher_icons: ^0.14.3
  share_plus: ^7.2.2
  google_fonts: ^6.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  xml: ^6.4.2
  path_provider: ^2.1.2
  geolocator: ^10.1.0
  permission_handler: ^11.3.1
  http: ^1.1.0
  # OCR機能のための新しい依存関係
  google_mlkit_text_recognition: ^0.11.0
  image_picker: ^1.0.7
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/launcher_icon/ios_icon.png
