// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Secure [FirebaseOptions] for use with your Firebase apps.
/// This version uses environment variables for sensitive data.
class SecureFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'SecureFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'SecureFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_WEB_API_KEY'] ?? '',
        appId: dotenv.env['FIREBASE_WEB_APP_ID'] ?? '',
        messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '',
        projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'rc-setting-manager',
        authDomain: dotenv.env['FIREBASE_AUTH_DOMAIN'] ??
            'rc-setting-manager.firebaseapp.com',
        storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ??
            'rc-setting-manager.firebasestorage.app',
        measurementId: dotenv.env['FIREBASE_MEASUREMENT_ID'] ?? '',
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ?? '',
        appId: dotenv.env['FIREBASE_ANDROID_APP_ID'] ?? '',
        messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '',
        projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'rc-setting-manager',
        storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ??
            'rc-setting-manager.firebasestorage.app',
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? '',
        appId: dotenv.env['FIREBASE_IOS_APP_ID'] ?? '',
        messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '',
        projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'rc-setting-manager',
        storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ??
            'rc-setting-manager.firebasestorage.app',
        iosBundleId: dotenv.env['FIREBASE_IOS_BUNDLE_ID'] ??
            'com.example.settingsheetManager',
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? '',
        appId: dotenv.env['FIREBASE_IOS_APP_ID'] ?? '',
        messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '',
        projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'rc-setting-manager',
        storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ??
            'rc-setting-manager.firebasestorage.app',
        iosBundleId: dotenv.env['FIREBASE_IOS_BUNDLE_ID'] ??
            'com.example.settingsheetManager',
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_WEB_API_KEY'] ?? '',
        appId: dotenv.env['FIREBASE_WINDOWS_APP_ID'] ?? '',
        messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '',
        projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'rc-setting-manager',
        authDomain: dotenv.env['FIREBASE_AUTH_DOMAIN'] ??
            'rc-setting-manager.firebaseapp.com',
        storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ??
            'rc-setting-manager.firebasestorage.app',
        measurementId: dotenv.env['FIREBASE_WINDOWS_MEASUREMENT_ID'] ?? '',
      );
}
