// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKIP88kAdkXBcWde69ofYkH3DGOQouwIE',
    appId: '1:375147888843:web:48d5233eb229bf1e235b4e',
    messagingSenderId: '375147888843',
    projectId: 'rc-setting-manager',
    authDomain: 'rc-setting-manager.firebaseapp.com',
    storageBucket: 'rc-setting-manager.firebasestorage.app',
    measurementId: 'G-P7JB663DCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnQdGoO5Tbn7ZbnsiRmRp1VbuVyylCRfM',
    appId: '1:375147888843:android:092e818accc5187c235b4e',
    messagingSenderId: '375147888843',
    projectId: 'rc-setting-manager',
    storageBucket: 'rc-setting-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6KsW_0rJCbYlRNM9Z3LeQWifq1HlppLQ',
    appId: '1:375147888843:ios:b8bdc6931e147db8235b4e',
    messagingSenderId: '375147888843',
    projectId: 'rc-setting-manager',
    storageBucket: 'rc-setting-manager.firebasestorage.app',
    iosBundleId: 'com.example.settingsheetManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6KsW_0rJCbYlRNM9Z3LeQWifq1HlppLQ',
    appId: '1:375147888843:ios:b8bdc6931e147db8235b4e',
    messagingSenderId: '375147888843',
    projectId: 'rc-setting-manager',
    storageBucket: 'rc-setting-manager.firebasestorage.app',
    iosBundleId: 'com.example.settingsheetManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKIP88kAdkXBcWde69ofYkH3DGOQouwIE',
    appId: '1:375147888843:web:7c3499ad54828e5f235b4e',
    messagingSenderId: '375147888843',
    projectId: 'rc-setting-manager',
    authDomain: 'rc-setting-manager.firebaseapp.com',
    storageBucket: 'rc-setting-manager.firebasestorage.app',
    measurementId: 'G-YD6V1NM4XX',
  );
}
