name: Build Development APK

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build Dev APK
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
    
    - name: Copy example google-services.json
      run: |
        cp android/app/google-services.json.example android/app/google-services.json
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Build Debug APK
      run: flutter build apk --debug
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk-${{ github.event.pull_request.number || github.run_number }}
        path: build/app/outputs/flutter-apk/app-debug.apk
    
    - name: Comment PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🎉 Debug APK has been built successfully! You can download it from the [Actions artifacts](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).'
          }) 